spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  thymeleaf:
    cache: false
  mail:
    host: smtp.sina.com
    port: 465
    username: wjd89ddd@sina.com
    password: 35604fde270907c2
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#  redis:
#    host: 192.168.29.128
#    port: 6379
#    database: 0
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0

#  jdbc:
#    template:
#      query-timeout: 3
#  boot:
#    admin:
#      client:
#        url: http://localhost:8888
#        instance:
#          prefer-ip: true  #使用ip注册进来
#  application:
#    name: boot-05-web-admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjd.nowcoder.entity
  configuration: # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    com.wjd.nowcoder: debug
server:
  port: 8080
  servlet:
    context-path: /community

community:
  path:
    domain: http://localhost:8080
    upload: E:/work/data/upload