server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://mysql:3306/cloud_user?useSSL=false
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
#      server-addr: nacos:8848 # nacos服务地址
      server-addr: localhost:8848 # nacos服务地址
#      server-addr: localhost:80 # nacos服务地址
#      discovery:
#        cluster-name: HZ # 集群名称
##        ephemeral: false # 是否是临时实例
#        namespace: a929eb11-8986-4497-bd8e-9a3da623da4a # dev环境

#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
##      discovery:
##        cluster-name: HZ
mybatis:
  type-aliases-package: com.wjd.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.wjd: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#pattern:
#  name: 本地环境local