spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456

#    druid:
#      aop-patterns: com.wjd.admin.*  #springbean监控
#      filters: stat,wall,slf4j  #所有开启的功能
#
#      stat-view-servlet: #监控页配置
#        enabled: true
#        login-username: admin
#        login-password: admin
#        resetEnable: false
#
#      web-stat-filter: #web监控
#        enabled: true
#        urlPattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
  # 配置类型别名所对应的包
  type-aliases-package: com.wjd.mybatisplus.pojo
  # 扫描通用枚举的包
  type-enums-package: com.wjd.mybatisplus.enums